name: plokitch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  google_fonts: ^8.1.0
  permission_handler: ^12.0.3
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  image_picker: ^1.2.3
  image: ^4.9.1
  file_picker: ^11.0.2
  sign_in_with_apple: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/plokitch_logo.png"
  adaptive_icon_background: "#35301D"
  adaptive_icon_foreground: "assets/images/plokitch_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env
  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
